package start.spring.app;

import java.util.Iterator;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class CurrencyJsonParser {

	public static String currencyJSON = "{\r\n"
			+ "  \"AED\": \"United Arab Emirates Dirham\",\r\n"
			+ "  \"AFN\": \"Afghan Afghani\",\r\n"
			+ "  \"ALL\": \"Albanian Lek\",\r\n"
			+ "  \"AMD\": \"Armenian Dram\",\r\n"
			+ "  \"ANG\": \"Netherlands Antillean Guilder\",\r\n"
			+ "  \"AOA\": \"Angolan Kwanza\",\r\n"
			+ "  \"ARS\": \"Argentine Peso\",\r\n"
			+ "  \"AUD\": \"Australian Dollar\",\r\n"
			+ "  \"AWG\": \"Aruban Florin\",\r\n"
			+ "  \"AZN\": \"Azerbaijani Manat\",\r\n"
			+ "  \"BAM\": \"Bosnia-Herzegovina Convertible Mark\",\r\n"
			+ "  \"BBD\": \"Barbadian Dollar\",\r\n"
			+ "  \"BDT\": \"Bangladeshi Taka\",\r\n"
			+ "  \"BGN\": \"Bulgarian Lev\",\r\n"
			+ "  \"BHD\": \"Bahraini Dinar\",\r\n"
			+ "  \"BIF\": \"Burundian Franc\",\r\n"
			+ "  \"BMD\": \"Bermudan Dollar\",\r\n"
			+ "  \"BND\": \"Brunei Dollar\",\r\n"
			+ "  \"BOB\": \"Bolivian Boliviano\",\r\n"
			+ "  \"BRL\": \"Brazilian Real\",\r\n"
			+ "  \"BSD\": \"Bahamian Dollar\",\r\n"
			+ "  \"BTC\": \"Bitcoin\",\r\n"
			+ "  \"BTN\": \"Bhutanese Ngultrum\",\r\n"
			+ "  \"BWP\": \"Botswanan Pula\",\r\n"
			+ "  \"BYN\": \"Belarusian Ruble\",\r\n"
			+ "  \"BZD\": \"Belize Dollar\",\r\n"
			+ "  \"CAD\": \"Canadian Dollar\",\r\n"
			+ "  \"CDF\": \"Congolese Franc\",\r\n"
			+ "  \"CHF\": \"Swiss Franc\",\r\n"
			+ "  \"CLF\": \"Chilean Unit of Account (UF)\",\r\n"
			+ "  \"CLP\": \"Chilean Peso\",\r\n"
			+ "  \"CNH\": \"Chinese Yuan (Offshore)\",\r\n"
			+ "  \"CNY\": \"Chinese Yuan\",\r\n"
			+ "  \"COP\": \"Colombian Peso\",\r\n"
			+ "  \"CRC\": \"Costa Rican Colón\",\r\n"
			+ "  \"CUC\": \"Cuban Convertible Peso\",\r\n"
			+ "  \"CUP\": \"Cuban Peso\",\r\n"
			+ "  \"CVE\": \"Cape Verdean Escudo\",\r\n"
			+ "  \"CZK\": \"Czech Republic Koruna\",\r\n"
			+ "  \"DJF\": \"Djiboutian Franc\",\r\n"
			+ "  \"DKK\": \"Danish Krone\",\r\n"
			+ "  \"DOP\": \"Dominican Peso\",\r\n"
			+ "  \"DZD\": \"Algerian Dinar\",\r\n"
			+ "  \"EGP\": \"Egyptian Pound\",\r\n"
			+ "  \"ERN\": \"Eritrean Nakfa\",\r\n"
			+ "  \"ETB\": \"Ethiopian Birr\",\r\n"
			+ "  \"EUR\": \"Euro\",\r\n"
			+ "  \"FJD\": \"Fijian Dollar\",\r\n"
			+ "  \"FKP\": \"Falkland Islands Pound\",\r\n"
			+ "  \"GBP\": \"British Pound Sterling\",\r\n"
			+ "  \"GEL\": \"Georgian Lari\",\r\n"
			+ "  \"GGP\": \"Guernsey Pound\",\r\n"
			+ "  \"GHS\": \"Ghanaian Cedi\",\r\n"
			+ "  \"GIP\": \"Gibraltar Pound\",\r\n"
			+ "  \"GMD\": \"Gambian Dalasi\",\r\n"
			+ "  \"GNF\": \"Guinean Franc\",\r\n"
			+ "  \"GTQ\": \"Guatemalan Quetzal\",\r\n"
			+ "  \"GYD\": \"Guyanaese Dollar\",\r\n"
			+ "  \"HKD\": \"Hong Kong Dollar\",\r\n"
			+ "  \"HNL\": \"Honduran Lempira\",\r\n"
			+ "  \"HRK\": \"Croatian Kuna\",\r\n"
			+ "  \"HTG\": \"Haitian Gourde\",\r\n"
			+ "  \"HUF\": \"Hungarian Forint\",\r\n"
			+ "  \"IDR\": \"Indonesian Rupiah\",\r\n"
			+ "  \"ILS\": \"Israeli New Sheqel\",\r\n"
			+ "  \"IMP\": \"Manx pound\",\r\n"
			+ "  \"INR\": \"Indian Rupee\",\r\n"
			+ "  \"IQD\": \"Iraqi Dinar\",\r\n"
			+ "  \"IRR\": \"Iranian Rial\",\r\n"
			+ "  \"ISK\": \"Icelandic Króna\",\r\n"
			+ "  \"JEP\": \"Jersey Pound\",\r\n"
			+ "  \"JMD\": \"Jamaican Dollar\",\r\n"
			+ "  \"JOD\": \"Jordanian Dinar\",\r\n"
			+ "  \"JPY\": \"Japanese Yen\",\r\n"
			+ "  \"KES\": \"Kenyan Shilling\",\r\n"
			+ "  \"KGS\": \"Kyrgystani Som\",\r\n"
			+ "  \"KHR\": \"Cambodian Riel\",\r\n"
			+ "  \"KMF\": \"Comorian Franc\",\r\n"
			+ "  \"KPW\": \"North Korean Won\",\r\n"
			+ "  \"KRW\": \"South Korean Won\",\r\n"
			+ "  \"KWD\": \"Kuwaiti Dinar\",\r\n"
			+ "  \"KYD\": \"Cayman Islands Dollar\",\r\n"
			+ "  \"KZT\": \"Kazakhstani Tenge\",\r\n"
			+ "  \"LAK\": \"Laotian Kip\",\r\n"
			+ "  \"LBP\": \"Lebanese Pound\",\r\n"
			+ "  \"LKR\": \"Sri Lankan Rupee\",\r\n"
			+ "  \"LRD\": \"Liberian Dollar\",\r\n"
			+ "  \"LSL\": \"Lesotho Loti\",\r\n"
			+ "  \"LYD\": \"Libyan Dinar\",\r\n"
			+ "  \"MAD\": \"Moroccan Dirham\",\r\n"
			+ "  \"MDL\": \"Moldovan Leu\",\r\n"
			+ "  \"MGA\": \"Malagasy Ariary\",\r\n"
			+ "  \"MKD\": \"Macedonian Denar\",\r\n"
			+ "  \"MMK\": \"Myanma Kyat\",\r\n"
			+ "  \"MNT\": \"Mongolian Tugrik\",\r\n"
			+ "  \"MOP\": \"Macanese Pataca\",\r\n"
			+ "  \"MRO\": \"Mauritanian Ouguiya (pre-2018)\",\r\n"
			+ "  \"MRU\": \"Mauritanian Ouguiya\",\r\n"
			+ "  \"MUR\": \"Mauritian Rupee\",\r\n"
			+ "  \"MVR\": \"Maldivian Rufiyaa\",\r\n"
			+ "  \"MWK\": \"Malawian Kwacha\",\r\n"
			+ "  \"MXN\": \"Mexican Peso\",\r\n"
			+ "  \"MYR\": \"Malaysian Ringgit\",\r\n"
			+ "  \"MZN\": \"Mozambican Metical\",\r\n"
			+ "  \"NAD\": \"Namibian Dollar\",\r\n"
			+ "  \"NGN\": \"Nigerian Naira\",\r\n"
			+ "  \"NIO\": \"Nicaraguan Córdoba\",\r\n"
			+ "  \"NOK\": \"Norwegian Krone\",\r\n"
			+ "  \"NPR\": \"Nepalese Rupee\",\r\n"
			+ "  \"NZD\": \"New Zealand Dollar\",\r\n"
			+ "  \"OMR\": \"Omani Rial\",\r\n"
			+ "  \"PAB\": \"Panamanian Balboa\",\r\n"
			+ "  \"PEN\": \"Peruvian Nuevo Sol\",\r\n"
			+ "  \"PGK\": \"Papua New Guinean Kina\",\r\n"
			+ "  \"PHP\": \"Philippine Peso\",\r\n"
			+ "  \"PKR\": \"Pakistani Rupee\",\r\n"
			+ "  \"PLN\": \"Polish Zloty\",\r\n"
			+ "  \"PYG\": \"Paraguayan Guarani\",\r\n"
			+ "  \"QAR\": \"Qatari Rial\",\r\n"
			+ "  \"RON\": \"Romanian Leu\",\r\n"
			+ "  \"RSD\": \"Serbian Dinar\",\r\n"
			+ "  \"RUB\": \"Russian Ruble\",\r\n"
			+ "  \"RWF\": \"Rwandan Franc\",\r\n"
			+ "  \"SAR\": \"Saudi Riyal\",\r\n"
			+ "  \"SBD\": \"Solomon Islands Dollar\",\r\n"
			+ "  \"SCR\": \"Seychellois Rupee\",\r\n"
			+ "  \"SDG\": \"Sudanese Pound\",\r\n"
			+ "  \"SEK\": \"Swedish Krona\",\r\n"
			+ "  \"SGD\": \"Singapore Dollar\",\r\n"
			+ "  \"SHP\": \"Saint Helena Pound\",\r\n"
			+ "  \"SLL\": \"Sierra Leonean Leone\",\r\n"
			+ "  \"SOS\": \"Somali Shilling\",\r\n"
			+ "  \"SRD\": \"Surinamese Dollar\",\r\n"
			+ "  \"SSP\": \"South Sudanese Pound\",\r\n"
			+ "  \"STD\": \"São Tomé and Príncipe Dobra (pre-2018)\",\r\n"
			+ "  \"STN\": \"São Tomé and Príncipe Dobra\",\r\n"
			+ "  \"SVC\": \"Salvadoran Colón\",\r\n"
			+ "  \"SYP\": \"Syrian Pound\",\r\n"
			+ "  \"SZL\": \"Swazi Lilangeni\",\r\n"
			+ "  \"THB\": \"Thai Baht\",\r\n"
			+ "  \"TJS\": \"Tajikistani Somoni\",\r\n"
			+ "  \"TMT\": \"Turkmenistani Manat\",\r\n"
			+ "  \"TND\": \"Tunisian Dinar\",\r\n"
			+ "  \"TOP\": \"Tongan Pa'anga\",\r\n"
			+ "  \"TRY\": \"Turkish Lira\",\r\n"
			+ "  \"TTD\": \"Trinidad and Tobago Dollar\",\r\n"
			+ "  \"TWD\": \"New Taiwan Dollar\",\r\n"
			+ "  \"TZS\": \"Tanzanian Shilling\",\r\n"
			+ "  \"UAH\": \"Ukrainian Hryvnia\",\r\n"
			+ "  \"UGX\": \"Ugandan Shilling\",\r\n"
			+ "  \"USD\": \"United States Dollar\",\r\n"
			+ "  \"UYU\": \"Uruguayan Peso\",\r\n"
			+ "  \"UZS\": \"Uzbekistan Som\",\r\n"
			+ "  \"VEF\": \"Venezuelan Bolívar Fuerte (Old)\",\r\n"
			+ "  \"VES\": \"Venezuelan Bolívar Soberano\",\r\n"
			+ "  \"VND\": \"Vietnamese Dong\",\r\n"
			+ "  \"VUV\": \"Vanuatu Vatu\",\r\n"
			+ "  \"WST\": \"Samoan Tala\",\r\n"
			+ "  \"XAF\": \"CFA Franc BEAC\",\r\n"
			+ "  \"XAG\": \"Silver Ounce\",\r\n"
			+ "  \"XAU\": \"Gold Ounce\",\r\n"
			+ "  \"XCD\": \"East Caribbean Dollar\",\r\n"
			+ "  \"XDR\": \"Special Drawing Rights\",\r\n"
			+ "  \"XOF\": \"CFA Franc BCEAO\",\r\n"
			+ "  \"XPD\": \"Palladium Ounce\",\r\n"
			+ "  \"XPF\": \"CFP Franc\",\r\n"
			+ "  \"XPT\": \"Platinum Ounce\",\r\n"
			+ "  \"YER\": \"Yemeni Rial\",\r\n"
			+ "  \"ZAR\": \"South African Rand\",\r\n"
			+ "  \"ZMW\": \"Zambian Kwacha\",\r\n"
			+ "  \"ZWL\": \"Zimbabwean Dollar\"\r\n"
			+ "}";
	
	public static void main(String[] args) {
		JsonObject jsonObject = (new JsonParser()).parse(currencyJSON).getAsJsonObject();


		jsonObject.keySet().forEach(keyStr ->
		    {
		        Object keyvalue = jsonObject.get(keyStr);
		        System.out.println("{ \"name\": \""+ keyStr + "\" },");

		        //for nested objects iteration if required
		        //if (keyvalue instanceof JSONObject)
		        //    printJsonObject((JSONObject)keyvalue);
		    });
	}
}
